#!/bin/sh
set -e

PACKAGE=lib64ncurses5-dev

if dpkg --compare-versions "$2" lt-nl 5.9-7; then
    # Replace directory with symlink.
    if [ ! -L /usr/share/doc/$PACKAGE ] && \
	[ -d /usr/share/doc/$PACKAGE ]; then
        if rmdir /usr/share/doc/$PACKAGE 2>/dev/null; then
            ln -sf libtinfo5 /usr/share/doc/$PACKAGE
        fi
    fi
fi

# Remove spurious symlink created by ldconfig (see #224450)
if [ "$1" = "configure" -a  -L /usr/lib64/libncurses.so.5 ]; then
    rm -f /usr/lib64/libncurses.so.5
fi

#DEBHELPER#

exit 0
