usr/include/*.h
usr/lib/libncurses.so
usr/lib/libtic.so
usr/lib/libform.so
usr/lib/libmenu.so
usr/lib/libpanel.so
usr/lib/pkgconfig/form.pc
usr/lib/pkgconfig/menu.pc
usr/lib/pkgconfig/ncurses++.pc
usr/lib/pkgconfig/ncurses.pc
usr/lib/pkgconfig/panel.pc
usr/lib/pkgconfig/tic.pc
obj-static/lib/libncurses.a usr/lib
obj-static/lib/libncurses++.a usr/lib
obj-static/lib/libtic.a usr/lib
obj-static/lib/libform.a usr/lib
obj-static/lib/libmenu.a usr/lib
obj-static/lib/libpanel.a usr/lib
